version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 'rocket_rides'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
      - 'db_data:/var/lib/postgresql/data'


volumes:
  db_data: